# Generated by Django 5.0.3 on 2024-04-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reminder_date', models.DateTimeField()),
                ('repetition_interval', models.CharField(choices=[('NO', 'No Repeat'), ('F5', 'Again 5 Minutes Later'), ('T25', 'Two Times Every 5 Minutes After First Reminder'), ('T35', 'Three Times Every 5 Minutes After First Reminder')], default='NO', max_length=3)),
                ('urgency', models.CharField(choices=[('NU', 'not urgent'), ('SU', 'slightly urgent'), ('VU', 'very urgent')], default='NU', max_length=2)),
            ],
        ),
    ]
