# Generated by Django 5.0.3 on 2024-04-18 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrem_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminder',
            name='urgency',
            field=models.CharField(choices=[('NU', 'Not Urgent'), ('SU', 'Slightly Urgent'), ('VU', 'Very Urgent')], default='NU', max_length=2),
        ),
    ]
