# Generated by Django 5.0.3 on 2024-04-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrem_app', '0002_reminder_user_alter_reminder_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
